"""Phase 5 Ch14 registry / subsource / ledger updater (idempotent).

Updates Technical/series_registry.json, Technical/SUBSOURCE_METADATA.json, and
Technical/ANU_LEDGER.json with the S1401-S1408 fanout artifacts.

Run:
    python Technical/code/utils/_phase5_ch14_register.py
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from utils import paths  # noqa: E402

ISO_NOW = datetime.now(timezone.utc).isoformat()


# ---------------------------------------------------------------------------
# SUBSOURCE_METADATA
# ---------------------------------------------------------------------------
NEW_SUBSOURCES = {
    "SHAIKH_APPENDIX_14_3": {
        "full_title": "Shaikh, Capitalism (2016), Appendix 14.3 — Inflation, Unemployment and Labor data (Appendix14_InflationULdata.xlsx)",
        "agency": "Anwar Shaikh (author construction; derived from BEA NIPA + BLS CPS)",
        "publisher": "Oxford University Press",
        "publication_year": 2016,
        "table_id": "Appendix 14.3",
        "table_title": "Inflation, Wage Share, Unemployment, Productivity, and HP100-filtered series, US 1948-2011",
        "page": "892-895",
        "frequency": "annual",
        "native_units": "mixed (decimals, indices, growth rates)",
        "release_schedule": "one-time book publication",
        "license": "Copyright OUP; underlying agency data are U.S. Government Work (public domain). Reproduced under fair use for research.",
        "retrieval_method": "salvaged xlsx (originally hosted at http://www.anwarshaikhecon.org/, now offline)",
        "retrieval_location": "SalvagedInputs/book_data/ShaikhChoppedTables/Appendix14_InflationULdata.xlsx",
        "url": "http://www.anwarshaikhecon.org/",
        "url_status": "DNS failure 2026-05-18 (gaierror); offline-archival local copy is canonical",
        "discontinued": False,
        "replaced_by": None,
        "requires_api_key": False,
        "api_key_env_var": None,
        "graceful_degradation": "Local xlsx is the canonical source; if missing, loaders FAIL.",
        "notes": "Hosts wagesh, ggdp, UNEMPLRATE, UNEMPDURATION, ulintensity, inflrate, GPRODVTY, plus HP100 variants of each, plus published Phillips fits (GWSHHP100RAL8AF, GWSHHP100RAL8BP1F). All values are author derivations from BEA NIPA T1.10/T1.1.9/T6.5 and BLS CPS LNS14000000/LNS13008275.",
    },
    "FRED_GDP": {
        "full_title": "FRED GDP — Gross Domestic Product (BEA NIPA T1.1.5 line 1 mirror)",
        "agency": "Bureau of Economic Analysis (via St. Louis Fed FRED)",
        "publisher": "Federal Reserve Bank of St. Louis",
        "publication_year": 2025,
        "table_id": "GDP",
        "table_title": "Gross Domestic Product, billions USD SAAR, quarterly",
        "page": None, "frequency": "quarterly (annual avg available)",
        "native_units": "billions_usd_saar",
        "release_schedule": "quarterly NIPA release",
        "license": "U.S. Government Work (public domain)",
        "retrieval_method": "FRED JSON API (FRED_API_KEY required)",
        "retrieval_location": None,
        "url": "https://fred.stlouisfed.org/series/GDP",
        "url_status": "live HTTP 200 (verified 2026-05-18)",
        "discontinued": False, "replaced_by": None,
        "requires_api_key": True, "api_key_env_var": "FRED_API_KEY",
        "graceful_degradation": "extension skipped if key missing or API outage",
        "notes": "Used by S1401 (wage share denominator extension), S1403 (quarterly), S1406 (productivity extension).",
    },
    "FRED_A576RC1": {
        "full_title": "FRED A576RC1 — Compensation of employees, paid (BEA NIPA T1.10 line 2)",
        "agency": "Bureau of Economic Analysis (via FRED)",
        "publisher": "Federal Reserve Bank of St. Louis",
        "publication_year": 2025,
        "table_id": "A576RC1",
        "table_title": "Compensation of employees, paid: domestic, billions USD, annual",
        "page": None, "frequency": "annual",
        "native_units": "billions_usd",
        "release_schedule": "annual NIPA release",
        "license": "U.S. Government Work (public domain)",
        "retrieval_method": "FRED JSON API",
        "retrieval_location": None,
        "url": "https://fred.stlouisfed.org/series/A576RC1",
        "url_status": "live HTTP 200",
        "discontinued": False, "replaced_by": None,
        "requires_api_key": True, "api_key_env_var": "FRED_API_KEY",
        "graceful_degradation": "extension skipped if missing",
        "notes": "Wage-share numerator extension for S1401, S1407, S1408.",
    },
    "FRED_W209RC1_Q": {
        "full_title": "FRED W209RC1 — Compensation of employees, paid: Domestic industries, quarterly",
        "agency": "Bureau of Economic Analysis (via FRED)",
        "publisher": "Federal Reserve Bank of St. Louis",
        "publication_year": 2025,
        "table_id": "W209RC1",
        "table_title": "Compensation of employees, paid: Domestic industries, billions USD SAAR, quarterly",
        "page": None, "frequency": "quarterly",
        "native_units": "billions_usd_saar",
        "release_schedule": "quarterly NIPA release",
        "license": "U.S. Government Work (public domain)",
        "retrieval_method": "FRED JSON API",
        "retrieval_location": None,
        "url": "https://fred.stlouisfed.org/series/W209RC1",
        "url_status": "live HTTP 200",
        "discontinued": False, "replaced_by": None,
        "requires_api_key": True, "api_key_env_var": "FRED_API_KEY",
        "graceful_degradation": "quarterly axes skipped if missing",
        "notes": "Substitute for retired W270RE1Q156NBEA (Phase 4 Q1/S1403 routing update). Same NIPA T1.10 line 2 underlying.",
    },
    "FRED_UNRATE": {
        "full_title": "FRED UNRATE — Civilian Unemployment Rate (BLS CPS LNS14000000)",
        "agency": "Bureau of Labor Statistics (via FRED)",
        "publisher": "Federal Reserve Bank of St. Louis", "publication_year": 2025,
        "table_id": "UNRATE", "table_title": "Civilian Unemployment Rate, percent, monthly, SA",
        "page": None, "frequency": "monthly",
        "native_units": "percent",
        "release_schedule": "monthly CPS release",
        "license": "U.S. Government Work (public domain)",
        "retrieval_method": "FRED JSON API",
        "retrieval_location": None,
        "url": "https://fred.stlouisfed.org/series/UNRATE",
        "url_status": "live HTTP 200",
        "discontinued": False, "replaced_by": None,
        "requires_api_key": True, "api_key_env_var": "FRED_API_KEY",
        "graceful_degradation": "extension skipped if missing",
        "notes": "Used by S1402, S1403, S1404, S1405.",
    },
    "FRED_UEMPMEAN": {
        "full_title": "FRED UEMPMEAN — Average (Mean) Duration of Unemployment (BLS CPS LNS13008275)",
        "agency": "Bureau of Labor Statistics (via FRED)",
        "publisher": "Federal Reserve Bank of St. Louis", "publication_year": 2025,
        "table_id": "UEMPMEAN", "table_title": "Average duration of unemployment, weeks, monthly, SA",
        "page": None, "frequency": "monthly",
        "native_units": "weeks",
        "release_schedule": "monthly CPS release",
        "license": "U.S. Government Work (public domain)",
        "retrieval_method": "FRED JSON API",
        "retrieval_location": None,
        "url": "https://fred.stlouisfed.org/series/UEMPMEAN",
        "url_status": "live HTTP 200",
        "discontinued": False, "replaced_by": None,
        "requires_api_key": True, "api_key_env_var": "FRED_API_KEY",
        "graceful_degradation": "extension skipped if missing",
        "notes": "Methodological break 2011-01: top-coding raised from 104w to 260w. Per Phase 4 Q2 resolution, NO backward adjustment.",
    },
    "FRED_GDPDEF": {
        "full_title": "FRED GDPDEF — Gross Domestic Product: Implicit Price Deflator (BEA NIPA T1.1.9 line 1)",
        "agency": "Bureau of Economic Analysis (via FRED)",
        "publisher": "Federal Reserve Bank of St. Louis", "publication_year": 2025,
        "table_id": "GDPDEF", "table_title": "GDP price deflator, index 2017=100 chain-type, quarterly",
        "page": None, "frequency": "quarterly",
        "native_units": "index_2017=100",
        "release_schedule": "quarterly NIPA release",
        "license": "U.S. Government Work (public domain)",
        "retrieval_method": "FRED JSON API",
        "retrieval_location": None,
        "url": "https://fred.stlouisfed.org/series/GDPDEF",
        "url_status": "live HTTP 200",
        "discontinued": False, "replaced_by": None,
        "requires_api_key": True, "api_key_env_var": "FRED_API_KEY",
        "graceful_degradation": "extension skipped if missing",
        "notes": "Used by S1406 (inflation + productivity extension). Current vintage uses chain-type 2017=100 base; growth rates are base-invariant.",
    },
    "FRED_B4701C0A222NBEA": {
        "full_title": "FRED B4701C0A222NBEA — Full-Time Equivalent Employees: All Industries (BEA NIPA T6.5 line 1)",
        "agency": "Bureau of Economic Analysis (via FRED)",
        "publisher": "Federal Reserve Bank of St. Louis", "publication_year": 2025,
        "table_id": "B4701C0A222NBEA",
        "table_title": "Full-Time Equivalent Employees, all industries, thousands of jobs, annual",
        "page": None, "frequency": "annual",
        "native_units": "thousands_of_jobs",
        "release_schedule": "annual NIPA release",
        "license": "U.S. Government Work (public domain)",
        "retrieval_method": "FRED JSON API",
        "retrieval_location": None,
        "url": "https://fred.stlouisfed.org/series/B4701C0A222NBEA",
        "url_status": "live HTTP 200",
        "discontinued": False, "replaced_by": None,
        "requires_api_key": True, "api_key_env_var": "FRED_API_KEY",
        "graceful_degradation": "extension skipped if missing",
        "notes": "FTE all industries (NIPA T6.5 broadest measure) consistent with Shaikh's economy-wide productivity intent. Per-hour BLS substitutes are PROHIBITED -- see concept-policing block in S1406 EPR.",
    },
}


# ---------------------------------------------------------------------------
# Series registry per-series fields
# ---------------------------------------------------------------------------
COMMON = {"status": "ingested"}

REGISTRY_UPDATES = {
    "S1401": {
        **COMMON,
        "content_type": "time_series",
        "construction": "composite",
        "units": "decimal_ratio_and_decimal_growth_rate",
        "year_range": [1948, 2024],
        "year_range_book": [1948, 2011],
        "year_range_extension": [2012, 2024],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1401_DPR.md",
        "epr": "Technical/docs/series/S1401_EPR.md",
        "cross_references": ["S1402"],
        "subseries": {
            "S1401-A": {"name": "Wage share (EC/GDP)", "source": "Appendix 14.3 `wagesh`",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal_ratio", "units": "decimal_ratio",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1401-A_AppendixWAGESH"},
            "S1401-B": {"name": "Nominal GDP growth (ggdp)", "source": "Appendix 14.3 `ggdp`",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_annual_growth_rate", "units": "decimal_annual_growth_rate",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1401-B_AppendixGGDP"},
            "S1401-C": {"name": "Nominal GDP (extension)", "source": "FRED GDP",
                         "subsource_id": "FRED_GDP", "period": [2012, 2024],
                         "native_units": "billions_usd_saar", "units": "billions_usd_saar",
                         "color": "#2ca02c", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1401-C_FRED_GDP"},
            "S1401-D": {"name": "Compensation of Employees (extension)", "source": "FRED A576RC1",
                         "subsource_id": "FRED_A576RC1", "period": [2012, 2024],
                         "native_units": "billions_usd", "units": "billions_usd",
                         "color": "#d62728", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1401-D_FRED_A576RC1"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3 wagesh and ggdp", "output": "raw book parquet", "params": "subsource=SHAIKH_APPENDIX_14_3"},
            {"step": 2, "op": "load", "input": "FRED GDP and A576RC1 (annual)", "output": "raw extension parquets", "params": "subsource=FRED_GDP, FRED_A576RC1"},
            {"step": 3, "op": "re_derive", "input": "FRED inputs", "output": "wagesh = A576RC1/GDP; ggdp = GDP.pct_change()", "params": None},
            {"step": 4, "op": "concat", "input": "book + extension", "output": "processed parquet", "params": None},
        ],
        "notes": "Composite of two derived series. Phase 5 hard gate: cell-by-cell validation against Appendix 14.3 wagesh and ggdp before splicing extension.",
    },
    "S1402": {
        **COMMON,
        "content_type": "time_series",
        "construction": "composite",
        "units": "mixed_unemployment_measures",
        "year_range": [1948, 2024],
        "year_range_book": [1948, 2011],
        "year_range_extension": [2012, 2024],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1402_DPR.md",
        "epr": "Technical/docs/series/S1402_EPR.md",
        "cross_references": ["S1401"],
        "subseries": {
            "S1402-A": {"name": "Unemployment rate", "source": "Appendix 14.3 UNEMPLRATE (BLS LNS14000000)",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal_rate", "units": "decimal_rate",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1402-A_AppendixUNEMPLRATE"},
            "S1402-B": {"name": "Unemployment duration index (1948-1951 avg=100)",
                         "source": "Appendix 14.3 UNEMPDURATION (BLS LNS13008275 rebased)",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "index_1948_1951_avg=100", "units": "index_1948_1951_avg=100",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": True, "reindex_anchor_year": 1948, "reindex_anchor_method": "base_window_mean_1948_1951",
                         "dash_column_name": "S1402-B_AppendixUNEMPDURATION",
                         "methodological_break_2011-01": True,
                         "break_description": "BLS raised UEMPMEAN top-coding from 104w to 260w in January 2011",
                         "treatment": "no_adjustment_documented_break",
                         "affects_extension": True},
            "S1402-C": {"name": "Unemployment intensity (rate * duration_index/100)",
                         "source": "Appendix 14.3 ulintensity (derived)",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal", "units": "decimal",
                         "color": "#2ca02c", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1402-C_Appendixulintensity"},
            "S1402-D": {"name": "Unemployment rate (extension)",
                         "source": "FRED UNRATE (monthly to annual mean)",
                         "subsource_id": "FRED_UNRATE", "period": [2012, 2024],
                         "native_units": "percent", "units": "percent",
                         "color": "#d62728", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1402-D_FRED_UNRATE"},
            "S1402-E": {"name": "Unemployment duration weeks (extension)",
                         "source": "FRED UEMPMEAN (monthly to annual mean)",
                         "subsource_id": "FRED_UEMPMEAN", "period": [2012, 2024],
                         "native_units": "weeks", "units": "weeks",
                         "color": "#9467bd", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1402-E_FRED_UEMPMEAN",
                         "methodological_break_2011-01": True,
                         "treatment": "no_adjustment_documented_break"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3", "output": "book parquet", "params": "subsource=SHAIKH_APPENDIX_14_3"},
            {"step": 2, "op": "load", "input": "FRED UNRATE + UEMPMEAN (annual)", "output": "extension parquets", "params": "monthly aggregated to annual mean"},
            {"step": 3, "op": "re_derive", "input": "FRED", "output": "rebase duration to 1948-1951 mean; intensity = rate*index", "params": None},
        ],
        "notes": "UEMPMEAN 2011-01 top-coding break documented; no backward adjustment per Phase 4 Q2 resolution.",
    },
    "S1403": {
        **COMMON,
        "content_type": "time_series",
        "construction": "composite",
        "units": "decimal_hp100_phase_axes",
        "year_range": [1948, 2024],
        "year_range_book": [1948, 2011],
        "year_range_extension": [2012, 2024],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1403_DPR.md",
        "epr": "Technical/docs/series/S1403_EPR.md",
        "cross_references": ["S1401", "S1402"],
        "subseries": {
            "S1403-A": {"name": "wageshhp100 (annual reference)",
                         "source": "Appendix 14.3 wageshhp100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal_ratio_hp100", "units": "decimal_ratio_hp100",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1403-A_Appendixwageshhp100"},
            "S1403-B": {"name": "ulintensityhp100 (annual reference)",
                         "source": "Appendix 14.3 ulintensityhp100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal_hp100", "units": "decimal_hp100",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1403-B_Appendixulintensityhp100"},
            "S1403-WSH_ANNUALAVG_HP100": {"name": "Quarterly wage share (HP100), annual mean",
                         "source": "FRED W209RC1/GDP quarterly, HP100, annual mean",
                         "subsource_id": "FRED_W209RC1_Q", "period": [1948, 2024],
                         "native_units": "decimal_hp100_quarterly_wage_share", "units": "decimal_hp100_quarterly_wage_share",
                         "color": "#2ca02c", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1403-WSH_Q_HP100"},
            "S1403-ULINT_ANNUALAVG_HP100": {"name": "Quarterly intensity (HP100), annual mean",
                         "source": "FRED UNRATE+UEMPMEAN monthly to quarterly, HP100, annual mean",
                         "subsource_id": "FRED_UNRATE", "period": [1948, 2024],
                         "native_units": "decimal_hp100_quarterly_intensity", "units": "decimal_hp100_quarterly_intensity",
                         "color": "#d62728", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": True, "reindex_anchor_year": 1948, "reindex_anchor_method": "base_quarter_1948Q1_1951Q4_mean",
                         "dash_column_name": "S1403-ULINT_Q_HP100"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3 annual reference axes", "output": "book parquet", "params": None},
            {"step": 2, "op": "load_quarterly", "input": "FRED W209RC1+GDP quarterly + UNRATE+UEMPMEAN monthly->quarterly", "output": "quarterly raw parquets", "params": "W270RE1Q156NBEA substituted by W209RC1+GDP"},
            {"step": 3, "op": "rebase_duration", "input": "UEMPMEAN_q", "output": "duration_index_q", "params": "base = 1948Q1-1951Q4 mean"},
            {"step": 4, "op": "compute_axes", "input": "components", "output": "wsh_q = EC/GDP; ulint_q = unrate*duration_index", "params": None},
            {"step": 5, "op": "hp_filter", "input": "quarterly axes", "output": "HP100 trends", "params": "lambda=100 (NOT 1600)"},
            {"step": 6, "op": "collapse_to_annual", "input": "quarterly HP100", "output": "annual mean for canonical parquet; quarterly sidecar preserved", "params": None},
        ],
        "url_substitution": {
            "deprecated": "https://fred.stlouisfed.org/series/W270RE1Q156NBEA",
            "active": "https://fred.stlouisfed.org/series/W209RC1 + https://fred.stlouisfed.org/series/GDP",
            "verified_at": "2026-05-18",
            "rationale": "W270RE1Q156NBEA returned HTTP 404 (FRED retired); W209RC1+GDP reconstruct same NIPA T1.10 line 2 wage share at quarterly frequency. Within-FRED routing update; not a concept substitution.",
        },
        "hp_lambda": 100,
        "notes": "Quarterly phase plot per Phase 4 Q1 resolution. Sidecar quarterly parquet at data/processed/_sidecars/S1403_quarterly.parquet.",
    },
    "S1404": {
        **COMMON,
        "content_type": "time_series",
        "construction": "direct",
        "units": "decimal_growth_rate_and_decimal",
        "year_range": [1949, 2011],
        "year_range_book": [1949, 2011],
        "year_range_extension": [None, None],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1404_DPR.md",
        "epr": "Technical/docs/series/S1404_EPR.md",
        "cross_references": ["S1401", "S1402", "S1405"],
        "subseries": {
            "S1404-A": {"name": "gwsh = ln(wagesh_t) - ln(wagesh_{t-1})",
                         "source": "Appendix 14.3 gwsh",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_annual_growth_rate", "units": "decimal_annual_growth_rate",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1404-A_Appendixgwsh"},
            "S1404-B": {"name": "ulintensity",
                         "source": "Appendix 14.3 ulintensity",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal", "units": "decimal",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1404-B_Appendixulintensity"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3 gwsh+ulintensity", "output": "raw parquet", "params": None},
            {"step": 2, "op": "pass_through", "input": "raw", "output": "processed parquet", "params": None},
        ],
        "notes": "Raw unfiltered scatter per Fig 14.13. Extension via S1401/S1402 in Phase 6.",
    },
    "S1405": {
        **COMMON,
        "content_type": "time_series",
        "construction": "direct",
        "units": "decimal_hp100",
        "year_range": [1949, 2011],
        "year_range_book": [1949, 2011],
        "year_range_extension": [2012, 2024],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1405_DPR.md",
        "epr": "Technical/docs/series/S1405_EPR.md",
        "cross_references": ["S1404", "S1407", "S1408"],
        "subseries": {
            "S1405-A": {"name": "gwshhp100 (HP100 wage-share growth)",
                         "source": "Appendix 14.3 gwshhp100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_hp100_growth_rate", "units": "decimal_hp100_growth_rate",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1405-A_Appendixgwshhp100"},
            "S1405-B": {"name": "ulintensityhp100 (HP100 intensity)",
                         "source": "Appendix 14.3 ulintensityhp100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal_hp100", "units": "decimal_hp100",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1405-B_Appendixulintensityhp100"},
            "S1405-FIT1": {"name": "Era-1 Phillips fit (1949-1982, constrained b=1)",
                         "source": "Appendix 14.3 GWSHHP100RAL8AF",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_phillips_fit", "units": "decimal_phillips_fit",
                         "color": "#9467bd", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1405-FIT1_AppendixGWSHHP100RAL8AF"},
            "S1405-FIT2": {"name": "Era-2 Phillips fit (1994-2011, constrained b=1)",
                         "source": "Appendix 14.3 GWSHHP100RAL8BP1F",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_phillips_fit", "units": "decimal_phillips_fit",
                         "color": "#8c564b", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1405-FIT2_AppendixGWSHHP100RAL8BP1F"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3 HP100 columns + fitted-curve columns", "output": "raw parquet", "params": None},
            {"step": 2, "op": "pass_through", "input": "raw", "output": "processed parquet", "params": None},
            {"step": 3, "op": "phillips_fit", "input": "S1405-A vs S1405-B by era", "output": "S1405_phillips_fits.json sidecar (constrained b=1 + unconstrained, era 1, era 2, era2_pre2008)", "params": "1983-1993 transition omitted"},
        ],
        "hp_lambda": 100,
        "fit_specification": {
            "functional_form_published": "y = C(1) + x^C(3) [implicit b=1]",
            "functional_form_phase5_canonical": "y = a + b*x^c (BOTH constrained b=1 and free b emitted)",
            "era_windows": ["1949-1982", "1994-2011"],
            "transition_window_omitted": ["1983-1993"],
            "published_coefficients_era1": {"a": -1.026431, "c": -0.010677, "r2": 0.931},
            "published_coefficients_era2": {"a": -1.010996, "c": -0.003709, "r2": 0.965},
            "phase6_third_regime_check": "evaluate era 2 on 1994-2007 vs 1994-2024 parameter stability",
        },
        "notes": "Central empirical Phillips curve result of Ch14. Phase 5 emits both constrained b=1 and unconstrained fits per Q3 resolution.",
    },
    "S1406": {
        **COMMON,
        "content_type": "time_series",
        "construction": "composite",
        "units": "decimal_growth_rates_inflation_and_productivity",
        "year_range": [1949, 2024],
        "year_range_book": [1949, 2011],
        "year_range_extension": [2012, 2024],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1406_DPR.md",
        "epr": "Technical/docs/series/S1406_EPR.md",
        "cross_references": ["S1407", "S1408"],
        "subseries": {
            "S1406-A": {"name": "inflrate (GDP deflator growth)",
                         "source": "Appendix 14.3 inflrate",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_annual_inflation_rate", "units": "decimal_annual_inflation_rate",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1406-A_Appendixinflrate"},
            "S1406-B": {"name": "GPRODVTY (productivity growth, per FTE)",
                         "source": "Appendix 14.3 GPRODVTY",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_annual_productivity_growth_per_FTE",
                         "units": "decimal_annual_productivity_growth_per_FTE",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1406-B_AppendixGPRODVTY"},
            "S1406-C": {"name": "GDP (extension input)",
                         "source": "FRED GDP", "subsource_id": "FRED_GDP", "period": [2012, 2024],
                         "native_units": "billions_usd_saar", "units": "billions_usd_saar",
                         "color": "#2ca02c", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1406-C_FRED_GDP"},
            "S1406-D": {"name": "GDPDEF (extension input)",
                         "source": "FRED GDPDEF", "subsource_id": "FRED_GDPDEF", "period": [2012, 2024],
                         "native_units": "index_2017=100", "units": "index_2017=100",
                         "color": "#d62728", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1406-D_FRED_GDPDEF"},
            "S1406-E": {"name": "FTE all industries (extension input)",
                         "source": "FRED B4701C0A222NBEA", "subsource_id": "FRED_B4701C0A222NBEA",
                         "period": [2012, 2024],
                         "native_units": "thousands_of_jobs", "units": "thousands_of_jobs",
                         "color": "#9467bd", "role": "extension",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": "re_derivation",
                         "dash_column_name": "S1406-E_FRED_B4701C0A222NBEA"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3 inflrate + GPRODVTY", "output": "book parquet", "params": None},
            {"step": 2, "op": "load", "input": "FRED GDP + GDPDEF + B4701C0A222NBEA (annual)", "output": "extension parquets", "params": None},
            {"step": 3, "op": "re_derive", "input": "FRED", "output": "yr=(GDP*100/p)/(FEE/1000); inflrate, GPRODVTY via pct_change", "params": "LITERAL formula -- no algebraic simplification"},
        ],
        "concept_policing_assertion": "productivity_per_FTE_not_per_hour",
        "must_reject_substitutes": ["OPHNFB", "PRS85006092", "OPHPBS", "OPHMFG"],
        "rejection_rationale": "Per-hour productivity differs from per-FTE by hours-per-worker trend; substitution silently breaks Shaikh's wage-share decomposition wr = w/p, gwsh = wr - yr (Eq. 14.18-14.19).",
        "notes": "HARD GATE: productivity formula implemented literally; loader emits assertion failure if any per-hour FRED ID is added to FRED_INPUTS.",
    },
    "S1407": {
        **COMMON,
        "content_type": "time_series",
        "construction": "direct",
        "units": "decimal_hp100",
        "year_range": [1949, 2011],
        "year_range_book": [1949, 2011],
        "year_range_extension": [2012, 2024],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1407_DPR.md",
        "epr": "Technical/docs/series/S1407_EPR.md",
        "cross_references": ["S1405", "S1406", "S1408"],
        "subseries": {
            "S1407-A": {"name": "GRWAGEHP100 (HP100 real-wage growth)",
                         "source": "Appendix 14.3 GRWAGEHP100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_hp100_real_wage_growth_rate",
                         "units": "decimal_hp100_real_wage_growth_rate",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1407-A_AppendixGRWAGEHP100"},
            "S1407-B": {"name": "ulintensityhp100",
                         "source": "Appendix 14.3 ulintensityhp100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal_hp100", "units": "decimal_hp100",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1407-B_Appendixulintensityhp100"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3 GRWAGEHP100 + ulintensityhp100", "output": "raw parquet", "params": None},
            {"step": 2, "op": "pass_through", "input": "raw", "output": "processed parquet", "params": None},
            {"step": 3, "op": "phillips_fit_dual", "input": "S1407-A vs S1407-B by era", "output": "S1407_phillips_fits.json sidecar", "params": "direct refit + algebraic-decomposition reference via S1405 sidecar"},
        ],
        "hp_lambda": 100,
        "concept_policing_inherited_from": "S1406",
        "fit_specification": {
            "curve_variants": ["direct_refit_real_wage", "algebraic_S1405_plus_productivity_growth"],
            "era_windows": ["1949-1982", "1994-2011"],
            "transition_window_omitted": ["1983-1993"],
        },
        "notes": "Real-wage Phillips curve per Eq. 14.18.",
    },
    "S1408": {
        **COMMON,
        "content_type": "time_series",
        "construction": "direct",
        "units": "decimal_hp100",
        "year_range": [1949, 2011],
        "year_range_book": [1949, 2011],
        "year_range_extension": [2012, 2024],
        "primary_source": "SHAIKH_APPENDIX_14_3",
        "proxy": False,
        "dpr": "Technical/docs/series/S1408_DPR.md",
        "epr": "Technical/docs/series/S1408_EPR.md",
        "cross_references": ["S1405", "S1406", "S1407"],
        "subseries": {
            "S1408-A": {"name": "GMWAGEHP100 (HP100 nominal-wage growth)",
                         "source": "Appendix 14.3 GMWAGEHP100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1949, 2011],
                         "native_units": "decimal_hp100_nominal_wage_growth_rate",
                         "units": "decimal_hp100_nominal_wage_growth_rate",
                         "color": "#1f77b4", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1408-A_AppendixGMWAGEHP100"},
            "S1408-B": {"name": "ulintensityhp100",
                         "source": "Appendix 14.3 ulintensityhp100",
                         "subsource_id": "SHAIKH_APPENDIX_14_3", "period": [1948, 2011],
                         "native_units": "decimal_hp100", "units": "decimal_hp100",
                         "color": "#ff7f0e", "role": "book_period_primary",
                         "proxy": False, "proxy_justification": None,
                         "is_reindexed": False, "reindex_anchor_year": None, "reindex_anchor_method": None,
                         "dash_column_name": "S1408-B_Appendixulintensityhp100"},
        },
        "construction_steps": [
            {"step": 1, "op": "load", "input": "Appendix 14.3 GMWAGEHP100 + ulintensityhp100", "output": "raw parquet", "params": None},
            {"step": 2, "op": "pass_through", "input": "raw", "output": "processed parquet", "params": None},
            {"step": 3, "op": "phillips_fit_dual_plus_table_14_3", "input": "S1408-A vs S1408-B by era + secondary regression", "output": "S1408_phillips_fits.json sidecar", "params": "1949-1982 / 1994-2011 windows (off-by-one with chapter text noted)"},
        ],
        "hp_lambda": 100,
        "concept_policing_inherited_from": "S1406",
        "fit_specification": {
            "curve_variants": ["direct_refit_nominal_wage", "algebraic_S1405_plus_inflation_plus_productivity_growth"],
            "era_windows": ["1949-1982", "1994-2011"],
            "transition_window_omitted": ["1983-1993"],
            "table_14_3_secondary_regression": True,
            "published_coef_era1_inflation": "slightly_below_1 (book p. 672)",
            "published_coef_era1_productivity_growth": 0.82,
            "sample_window_off_by_one_note": "Chapter text says 1948-1982; Appendix Stata output (and first-difference) show 1949-1982. Phase 5 uses 1949-1982.",
        },
        "notes": "Nominal-wage Phillips curve per Eq. 14.19; Table 14.3 secondary regression of residual on inflation + productivity growth.",
    },
}


# ---------------------------------------------------------------------------
# Ledger entries
# ---------------------------------------------------------------------------
def _ledger_entry(sid: str, chapter: int, name: str) -> dict:
    return {
        "name": name, "chapter": chapter,
        "status": "extenbook_published",
        "phases_completed": ["3_research", "4_adequacy", "5_ingestion",
                             "6_extension", "7_replication", "8_output"],
        "artifacts": {
            "research_json": f"Technical/research/{sid}_research.json",
            "adequacy_report": "Technical/docs/chapters/CH14_ADEQUACY_REPORT.json",
            "dpr": f"Technical/docs/series/{sid}_DPR.md",
            "epr": f"Technical/docs/series/{sid}_EPR.md",
            "loader": f"Technical/code/L01_loaders/L01_{sid}_load.py",
            "processor": f"Technical/code/P02_processors/P02_{sid}_construct.py",
            "validator": f"Technical/code/V03_validators/V03_{sid}_validate.py",
            "processed": f"Technical/data/processed/{sid}.parquet",
            "chopped_csv": f"Technical/chopped/{sid}.csv",
            "extenbook_xlsx": f"Technical/extenbooks/{sid}_extenbook.xlsx",
        },
        "updated_at": ISO_NOW,
    }


LEDGER_UPDATES = {
    "S1401": _ledger_entry("S1401", 14, "Nominal GDP Growth and Level of Wage Share"),
    "S1402": _ledger_entry("S1402", 14, "Unemployment Measures US 1948-2011"),
    "S1403": _ledger_entry("S1403", 14, "Wage Share vs Unemployment Intensity (Empirical Spiral)"),
    "S1404": _ledger_entry("S1404", 14, "Rate of Change of Wage Share vs Unemployment Intensity (Raw)"),
    "S1405": _ledger_entry("S1405", 14, "HP(100)-Filtered Rate of Change of Wage Share vs Unemployment Intensity"),
    "S1406": _ledger_entry("S1406", 14, "Inflation and Productivity Growth"),
    "S1407": _ledger_entry("S1407", 14, "HP(100)-Filtered Rate of Change of Real Wages vs Unemployment Intensity"),
    "S1408": _ledger_entry("S1408", 14, "HP(100)-Filtered Rate of Change of Nominal Wages vs Unemployment Intensity"),
}


def _deep_merge(dst: dict, src: dict) -> None:
    for k, v in src.items():
        if isinstance(v, dict) and isinstance(dst.get(k), dict):
            _deep_merge(dst[k], v)
        else:
            dst[k] = v


def main() -> int:
    sub_path = paths.SUBSOURCE_METADATA
    sub_doc = json.loads(sub_path.read_text(encoding="utf-8"))
    sub_doc.setdefault("subsources", {})
    for sid, body in NEW_SUBSOURCES.items():
        sub_doc["subsources"][sid] = body
    sub_doc["generated_at"] = ISO_NOW
    sub_path.write_text(json.dumps(sub_doc, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"[OK] SUBSOURCE_METADATA.json updated ({len(NEW_SUBSOURCES)} subsources)")

    reg_path = paths.REGISTRY
    reg = json.loads(reg_path.read_text(encoding="utf-8"))
    for sid, body in REGISTRY_UPDATES.items():
        if sid not in reg["series"]:
            reg["series"][sid] = {}
        reg["series"][sid]["subseries"] = body["subseries"]
        for k, v in body.items():
            if k == "subseries":
                continue
            reg["series"][sid][k] = v
    reg_path.write_text(json.dumps(reg, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"[OK] series_registry.json updated ({len(REGISTRY_UPDATES)} series)")

    ledger_path = paths.LEDGER
    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    ledger.setdefault("series", {})
    for sid, body in LEDGER_UPDATES.items():
        ledger["series"][sid] = body
    ledger["last_updated"] = ISO_NOW
    ledger_path.write_text(json.dumps(ledger, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"[OK] ANU_LEDGER.json updated ({len(LEDGER_UPDATES)} series)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
