"""One-shot updater for CH10 registry + SUBSOURCE_METADATA + ANU_LEDGER.

Run once after authoring CH10 artifacts; idempotent (safe to re-run).
"""
import json
from pathlib import Path

PROJ = Path(__file__).resolve().parents[2]
REG = PROJ / "series_registry.json"
META = PROJ / "SUBSOURCE_METADATA.json"
LED = PROJ / "ANU_LEDGER.json"

reg = json.loads(REG.read_text(encoding="utf-8"))
meta = json.loads(META.read_text(encoding="utf-8"))
led = json.loads(LED.read_text(encoding="utf-8"))

CH10 = {
    "S1001": {
        "construction": "composite",
        "units": "rate_decimal",
        "primary_source": "SHAIKH_APP72_BANKS",
        "year_range": [1988, 2005],
        "year_range_book": [1988, 2005],
        "year_range_extension": [None, None],
        "subseries": {
            "S1001-A": {"name": "Banking IROP (Shaikh App.7.2 Banks column)", "subsource_id": "SHAIKH_APP72_BANKS",
                        "period": [1988, 2005], "units": "rate_decimal", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1001-B": {"name": "All Private avg IROP", "subsource_id": "SHAIKH_APP72_ALLPRIV",
                        "period": [1988, 2005], "units": "rate_decimal", "color": "#ff7f0e",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
        },
    },
    "S1002": {
        "construction": "composite",
        "units": "mixed_percent_and_index_1947=100",
        "primary_source": "USLR_iblong",
        "year_range": [1857, 2030],
        "year_range_book": [1857, 2011],
        "year_range_extension": [2012, 2030],
        "subseries": {
            "S1002-A": {"name": "Composite long bond yield (Macaulay+Aaa)", "subsource_id": "USLR_iblong",
                        "period": [1857, 2011], "units": "percent", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1002-B": {"name": "Composite PPI 1947=100", "subsource_id": "USLR_USWPI",
                        "period": [1780, 2011], "units": "index_1947=100", "color": "#ff7f0e",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1002-C": {"name": "FRED AAA extension", "subsource_id": "FRED_AAA",
                        "period": [2012, 2030], "units": "percent", "color": "#2ca02c",
                        "role": "extension", "proxy": False, "proxy_justification": None},
            "S1002-D": {"name": "FRED PPIACO extension reindexed to 1947=100", "subsource_id": "FRED_PPIACO",
                        "period": [2012, 2030], "units": "index_1947=100", "color": "#d62728",
                        "role": "extension", "proxy": False, "proxy_justification": None},
        },
    },
    "S1003": {
        "construction": "formula",
        "units": "ratio_1947=1",
        "primary_source": "USLR_ibp",
        "year_range": [1857, 2030],
        "year_range_book": [1857, 2011],
        "year_range_extension": [2012, 2030],
        "formula": "rpf_t = (iblong_t/iblong_1947) / (USWPI_t/USWPI_1947)",
        "components": ["S1002-A/C", "S1002-B/D"],
        "subseries": {
            "S1003-A": {"name": "RPF book period", "subsource_id": "S1002_components_book",
                        "period": [1857, 2011], "units": "ratio_1947=1", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1003-B": {"name": "RPF extension (recomputed from extended components)",
                        "subsource_id": "S1002_components_extended",
                        "period": [2012, 2030], "units": "ratio_1947=1", "color": "#2ca02c",
                        "role": "extension", "proxy": False, "proxy_justification": None},
        },
    },
    "S1004": {
        "construction": "formula",
        "units": "percent",
        "primary_source": "USLR_iblongreal",
        "year_range": [1858, 2030],
        "year_range_book": [1858, 2011],
        "year_range_extension": [2012, 2030],
        "formula": "iblongreal_t = iblong_t - (USWPI_t/USWPI_{t-1}-1)*100; HP filter on full panel lambda in {3, 6.25}",
        "components": ["S1002-A/C", "S1002-B/D"],
        "subseries": {
            "S1004-A": {"name": "Real long bond yield (book recomputed)", "subsource_id": "S1002_components",
                        "period": [1858, 2011], "units": "percent", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1004-B": {"name": "HP-filtered lambda=3 (book replication)", "subsource_id": "HP_filter_lambda_3",
                        "period": [1858, 2030], "units": "percent", "color": "#ff7f0e",
                        "role": "derived_smoothed", "proxy": False, "proxy_justification": None},
            "S1004-C": {"name": "HP-filtered lambda=6.25 (Ravn-Uhlig)", "subsource_id": "HP_filter_lambda_6.25",
                        "period": [1858, 2030], "units": "percent", "color": "#9467bd",
                        "role": "derived_smoothed_sensitivity", "proxy": False, "proxy_justification": None},
            "S1004-D": {"name": "Real rate extension (recomputed)", "subsource_id": "S1002_components",
                        "period": [2012, 2030], "units": "percent", "color": "#2ca02c",
                        "role": "extension", "proxy": False, "proxy_justification": None},
        },
    },
    "S1005": {
        "construction": "composite",
        "units": "percent",
        "primary_source": "USLR_ys",
        "year_range": [1871, 2030],
        "year_range_book": [1871, 2011],
        "year_range_extension": [2012, 2030],
        "subseries": {
            "S1005-A": {"name": "Shiller S&P dividend yield (book)", "subsource_id": "USLR_ys",
                        "period": [1871, 2011], "units": "percent", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1005-A-ext": {"name": "Shiller ie_data.xls extension", "subsource_id": "SHILLER_ie_data",
                            "period": [2012, 2030], "units": "percent", "color": "#1f77b4",
                            "role": "extension", "proxy": False, "proxy_justification": None},
            "S1005-B": {"name": "10yr govt yield (book)", "subsource_id": "USLR_ib10yr",
                        "period": [1871, 2011], "units": "percent", "color": "#ff7f0e",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1005-B-ext": {"name": "FRED GS10 extension", "subsource_id": "FRED_GS10",
                            "period": [2012, 2030], "units": "percent", "color": "#ff7f0e",
                            "role": "extension", "proxy": False, "proxy_justification": None},
            "S1005-C": {"name": "Corp composite yield (= S1002-A)", "subsource_id": "USLR_iblong",
                        "period": [1857, 2011], "units": "percent", "color": "#2ca02c",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1005-C-ext": {"name": "FRED AAA extension (= S1002-C)", "subsource_id": "FRED_AAA",
                            "period": [2012, 2030], "units": "percent", "color": "#2ca02c",
                            "role": "extension", "proxy": False, "proxy_justification": None},
        },
    },
    "S1006": {
        "construction": "composite",
        "units": "percent_total_return_nominal",
        "primary_source": "IBBOTSON_SBBI_2004",
        "year_range": [1926, 2030],
        "year_range_book": [1926, 2010],
        "year_range_extension": [2011, 2030],
        "subseries": {
            "S1006-A": {"name": "Large Company Stocks total return (Ibbotson, book)", "subsource_id": "IBBOTSON_SBBI_rslarge",
                        "period": [1926, 2010], "units": "percent_total_return", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1006-A-ext": {"name": "S&P 500 total return (Damodaran NYU)", "subsource_id": "DAMODARAN_rslarge",
                            "period": [2011, 2030], "units": "percent_total_return", "color": "#1f77b4",
                            "role": "extension", "proxy": False,
                            "proxy_justification": "Damodaran S&P 500 (includes dividends) is the open-license successor to Ibbotson SBBI Large Company Stocks; same index/convention."},
            "S1006-B": {"name": "LT Corp Bonds total return (Ibbotson, book)", "subsource_id": "IBBOTSON_SBBI_rbcorplt",
                        "period": [1926, 2010], "units": "percent_total_return", "color": "#ff7f0e",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1006-B-ext": {"name": "LT Corp Bonds proxy (FRED AAA yield)", "subsource_id": "FRED_AAA_proxy_LTcorp",
                            "period": [2011, 2030], "units": "percent_yield_proxy_for_total_return", "color": "#ff7f0e",
                            "role": "extension_proxy", "proxy": True,
                            "proxy_justification": "FRED AAA yield approximates running-yield component of Ibbotson ~20yr investment-grade LT corp total return. Omits capital-gain component. See S1006_EPR.md."},
            "S1006-B-ext-damodaran": {"name": "LT Corp Bonds proxy (Damodaran Baa yield)", "subsource_id": "DAMODARAN_rbcorplt_Baa",
                                       "period": [2011, 2030], "units": "percent_yield_proxy_for_total_return", "color": "#ff7f0e",
                                       "role": "extension_proxy_alternate", "proxy": True,
                                       "proxy_justification": "Damodaran publishes Baa corporate bond yield (one notch lower credit than Ibbotson Aaa); used as alternate open-license proxy for LT corp total return. Omits capital-gain component. See S1006_EPR.md."},
            "S1006-C": {"name": "LT Govt Bonds total return (Ibbotson, book)", "subsource_id": "IBBOTSON_SBBI_rbgovlt",
                        "period": [1926, 2010], "units": "percent_total_return", "color": "#2ca02c",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1006-C-ext": {"name": "10yr UST total return (Damodaran NYU)", "subsource_id": "DAMODARAN_rbgovlt",
                            "period": [2011, 2030], "units": "percent_total_return", "color": "#2ca02c",
                            "role": "extension", "proxy": False,
                            "proxy_justification": "Damodaran 10yr T.Bond substitutes Ibbotson ~20yr Long-Term Government Bonds; duration spread sensitivity acknowledged."},
        },
    },
    "S1007": {
        "construction": "composite",
        "units": "rate_decimal",
        "primary_source": "INTROPPRICE_rreq",
        "year_range": [1948, 2011],
        "year_range_book": [1948, 2011],
        "year_range_extension": [None, None],
        "subseries": {
            "S1007-A": {"name": "Real equity rate of return rreq", "subsource_id": "INTROPPRICE_rreq",
                        "period": [1948, 2011], "units": "rate_decimal", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1007-B": {"name": "Adjusted corporate real IROP", "subsource_id": "INTROPPRICE_iropcorp",
                        "period": [1948, 2011], "units": "rate_decimal", "color": "#ff7f0e",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1007-C": {"name": "NIPA corporate real IROP", "subsource_id": "INTROPPRICE_iropcorpnipa",
                        "period": [1948, 2011], "units": "rate_decimal", "color": "#2ca02c",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
        },
    },
    "S1008": {
        "construction": "composite",
        "units": "index_real_BEA_deflator",
        "primary_source": "INTROPPRICE_preq",
        "year_range": [1947, 2011],
        "year_range_book": [1947, 2011],
        "year_range_extension": [None, None],
        "formula": "prweq_t = prweq_{t-1}*(1+rI_t) - dvr_t  [eq 10.31]; PINNED NORMALIZATION_INTERVAL = (1948, 2011) per footnote 24",
        "components": ["S1008-A preq", "S1008-DVR dvr", "S1007-B rI"],
        "subseries": {
            "S1008-A": {"name": "Real equity price preq", "subsource_id": "INTROPPRICE_preq",
                        "period": [1947, 2011], "units": "index_real_BEA_deflator", "color": "#1f77b4",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1008-B": {"name": "Shiller P* re-deflated prstarshiller1", "subsource_id": "INTROPPRICE_prstarshiller1",
                        "period": [1947, 2009], "units": "index_real_BEA_deflator", "color": "#ff7f0e",
                        "role": "book_primary", "proxy": False, "proxy_justification": None},
            "S1008-C": {"name": "Warranted real equity price prweq (eq 10.31, pinned init)",
                        "subsource_id": "eq_10.31_recursion",
                        "period": [1947, 2011], "units": "index_real_BEA_deflator", "color": "#2ca02c",
                        "role": "derived_recursion", "proxy": False, "proxy_justification": None},
        },
    },
}

for sid, payload in CH10.items():
    s = reg["series"].get(sid, {})
    s["construction"] = payload["construction"]
    s["units"] = payload["units"]
    s["primary_source"] = payload["primary_source"]
    s["year_range"] = payload["year_range"]
    s["year_range_book"] = payload["year_range_book"]
    s["year_range_extension"] = payload["year_range_extension"]
    s["subseries"] = payload["subseries"]
    s["status"] = "ingested"
    if "formula" in payload:
        s["formula"] = payload["formula"]
    if "components" in payload:
        s["components"] = payload["components"]
    s["dpr"] = f"Technical/docs/series/{sid}_DPR.md"
    s["epr"] = f"Technical/docs/series/{sid}_EPR.md"
    reg["series"][sid] = s

REG.write_text(json.dumps(reg, indent=2, default=str), encoding="utf-8")
print(f"Registry updated for {len(CH10)} CH10 series.")

NEW_SUBS = {
    "SHAIKH_APP72_BANKS": {"agency": "Shaikh (App 7.2)", "publication": "Capitalism (2016) App 7.2 Banks column",
                            "full_title": "Banking industry IROP (Shaikh Appendix 7.2)",
                            "table_id": "Appendix7_iropdataUSind.xlsx col Banks",
                            "frequency": "annual", "native_units": "rate_decimal",
                            "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                            "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                            "discontinued": True, "graceful_degradation_notes": "companion site DNS-dead; local SalvagedInputs canonical"},
    "SHAIKH_APP72_ALLPRIV": {"agency": "Shaikh (App 7.2)", "publication": "App 7.2 All Private column",
                              "full_title": "All-Private cross-industry IROP",
                              "table_id": "Appendix7_iropdataUSind.xlsx col All Private",
                              "frequency": "annual", "native_units": "rate_decimal",
                              "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                              "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                              "discontinued": True, "graceful_degradation_notes": "companion site DNS-dead"},
    "USLR_iblong": {"agency": "NBER+FRB+ERP", "publication": "Shaikh App 10.2 USLR col iblong",
                     "full_title": "Composite long bond yield (Macaulay 1857-1937 + Aaa 1938-2011)",
                     "table_id": "Appendix10_USLR.xlsx col iblong", "frequency": "annual", "native_units": "percent",
                     "license": "Public-domain (US govt + NBER)", "retrieval_method": "salvaged_local_xlsx",
                     "url": "https://data.nber.org/databases/macrohistory/rectdata/13/m13019.dat",
                     "discontinued": False, "graceful_degradation_notes": ""},
    "USLR_USWPI": {"agency": "Jastram 1977 + BLS", "publication": "Shaikh App 10.2 USLR col USWPI",
                    "full_title": "Composite PPI 1947=100", "table_id": "Appendix10_USLR.xlsx col USWPI",
                    "frequency": "annual", "native_units": "index_1947=100",
                    "license": "Public-domain (BLS) + Jastram academic", "retrieval_method": "salvaged_local_xlsx",
                    "url": "https://fred.stlouisfed.org/graph/fredgraph.csv?id=PPIACO",
                    "discontinued": False, "graceful_degradation_notes": ""},
    "USLR_ibp": {"agency": "Shaikh (derived)", "publication": "Shaikh App 10.2 USLR col ib/p",
                  "full_title": "Relative price of finance (book derived)",
                  "table_id": "Appendix10_USLR.xlsx col ib/p", "frequency": "annual", "native_units": "ratio_1947=1",
                  "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                  "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                  "discontinued": False, "graceful_degradation_notes": ""},
    "USLR_iblongreal": {"agency": "Shaikh (derived)", "publication": "Shaikh App 10.2 USLR cols iblongreal/iblongrealHP3",
                         "full_title": "Real long bond yield + HP smoothed", "table_id": "Appendix10_USLR.xlsx",
                         "frequency": "annual", "native_units": "percent",
                         "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                         "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                         "discontinued": False, "graceful_degradation_notes": ""},
    "USLR_ys": {"agency": "Shiller", "publication": "Shaikh App 10.2 USLR col ys",
                 "full_title": "Shiller S&P dividend yield (annual)", "table_id": "Appendix10_USLR.xlsx col ys",
                 "frequency": "annual", "native_units": "percent",
                 "license": "Academic free-use (Shiller)", "retrieval_method": "salvaged_local_xlsx",
                 "url": "http://www.econ.yale.edu/~shiller/data.htm",
                 "discontinued": False, "graceful_degradation_notes": ""},
    "USLR_ib10yr": {"agency": "Shiller/FRB", "publication": "Shaikh App 10.2 USLR col ib10yr Gov",
                     "full_title": "10-year US govt bond yield", "table_id": "Appendix10_USLR.xlsx col ib10yr Gov",
                     "frequency": "annual", "native_units": "percent",
                     "license": "Academic free-use", "retrieval_method": "salvaged_local_xlsx",
                     "url": "http://www.econ.yale.edu/~shiller/data.htm",
                     "discontinued": False, "graceful_degradation_notes": ""},
    "FRED_AAA": {"agency": "Federal Reserve Board / Moody's via St. Louis Fed", "publication": "FRED AAA",
                  "full_title": "Moody's Aaa corporate bond yield, monthly->annual mean",
                  "table_id": "AAA", "frequency": "monthly", "native_units": "percent",
                  "license": "FRED Terms of Use (public-domain)", "retrieval_method": "live_csv",
                  "url": "https://fred.stlouisfed.org/graph/fredgraph.csv?id=AAA",
                  "discontinued": False, "graceful_degradation_notes": "csv endpoint key-free; stable"},
    "FRED_PPIACO": {"agency": "BLS via St. Louis Fed", "publication": "FRED PPIACO",
                    "full_title": "BLS PPI All Commodities, monthly->annual mean",
                    "table_id": "PPIACO", "frequency": "monthly", "native_units": "index_1982=100",
                    "license": "FRED Terms of Use", "retrieval_method": "live_csv",
                    "url": "https://fred.stlouisfed.org/graph/fredgraph.csv?id=PPIACO",
                    "discontinued": False, "graceful_degradation_notes": ""},
    "FRED_GS10": {"agency": "FRB via St. Louis Fed", "publication": "FRED GS10",
                   "full_title": "10yr UST constant maturity yield", "table_id": "GS10",
                   "frequency": "monthly", "native_units": "percent",
                   "license": "FRED Terms of Use", "retrieval_method": "live_csv",
                   "url": "https://fred.stlouisfed.org/graph/fredgraph.csv?id=GS10",
                   "discontinued": False, "graceful_degradation_notes": ""},
    "SHILLER_ie_data": {"agency": "Robert Shiller, Yale", "publication": "ie_data.xls",
                         "full_title": "Shiller US Stock Market Data workbook",
                         "table_id": "Data sheet of ie_data.xls",
                         "frequency": "monthly", "native_units": "mixed",
                         "license": "Academic free-use", "retrieval_method": "live_xls",
                         "url": "http://www.econ.yale.edu/~shiller/data/ie_data.xls",
                         "discontinued": False, "graceful_degradation_notes": "OLE2 legacy; requires xlrd"},
    "SHILLER_div": {"agency": "Robert Shiller, Yale", "publication": "ie_data.xls D/P annual",
                     "full_title": "Shiller S&P dividend yield (D/P*100 annual mean)",
                     "table_id": "Data sheet cols D and P",
                     "frequency": "monthly->annual", "native_units": "percent",
                     "license": "Academic free-use", "retrieval_method": "live_xls",
                     "url": "http://www.econ.yale.edu/~shiller/data/ie_data.xls",
                     "discontinued": False, "graceful_degradation_notes": ""},
    "IBBOTSON_SBBI_rslarge": {"agency": "Ibbotson Associates (now Morningstar SBBI)",
                                "publication": "SBBI 2004 Yearbook table 2-2",
                                "full_title": "Large Company Stocks total return (S&P 500 since 1957)",
                                "table_id": "Appendix10_Ibbotson.xlsx col 'Large Company Stocks'",
                                "frequency": "annual", "native_units": "percent_total_return",
                                "license": "Academic reference; modern Morningstar SBBI is commercial",
                                "retrieval_method": "salvaged_local_xlsx",
                                "url": "https://www.morningstar.com/products/ibbotson-sbbi",
                                "discontinued": False, "graceful_degradation_notes": "Modern via Damodaran NYU per decision 0005"},
    "IBBOTSON_SBBI_rbcorplt": {"agency": "Ibbotson Associates", "publication": "SBBI 2004 table 2-2",
                                 "full_title": "LT Corporate Bonds total return (~20yr investment-grade)",
                                 "table_id": "Appendix10_Ibbotson.xlsx col 'Long-Term Corporate Bonds'",
                                 "frequency": "annual", "native_units": "percent_total_return",
                                 "license": "Academic reference",
                                 "retrieval_method": "salvaged_local_xlsx",
                                 "url": "https://www.morningstar.com/products/ibbotson-sbbi",
                                 "discontinued": False, "graceful_degradation_notes": "Extension is a PROXY (AAA yield); see S1006_EPR.md"},
    "IBBOTSON_SBBI_rbgovlt": {"agency": "Ibbotson Associates", "publication": "SBBI 2004 table 2-2",
                                "full_title": "LT Government Bonds total return (~20yr UST)",
                                "table_id": "Appendix10_Ibbotson.xlsx col 'Long-Term Government Bonds'",
                                "frequency": "annual", "native_units": "percent_total_return",
                                "license": "Academic reference",
                                "retrieval_method": "salvaged_local_xlsx",
                                "url": "https://www.morningstar.com/products/ibbotson-sbbi",
                                "discontinued": False, "graceful_degradation_notes": "Modern via Damodaran 10yr T.Bond"},
    "DAMODARAN_rslarge": {"agency": "Aswath Damodaran, NYU Stern",
                            "publication": "Historical Returns: Stocks, T.Bonds & T.Bills with Premiums",
                            "full_title": "S&P 500 total return incl. dividends, nominal annual",
                            "table_id": "histretSP.html col S&P 500 (includes dividends)",
                            "frequency": "annual", "native_units": "percent_total_return",
                            "license": "Open academic (free posted by author)",
                            "retrieval_method": "live_html",
                            "url": "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/histretSP.html",
                            "discontinued": False, "graceful_degradation_notes": "Annual to T-1; substitutes Ibbotson per decision 0005"},
    "DAMODARAN_rbgovlt": {"agency": "Aswath Damodaran, NYU Stern", "publication": "Historical Returns",
                            "full_title": "10yr US T.Bond total return, nominal annual",
                            "table_id": "histretSP.html col US T. Bond",
                            "frequency": "annual", "native_units": "percent_total_return",
                            "license": "Open academic", "retrieval_method": "live_html",
                            "url": "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/histretSP.html",
                            "discontinued": False, "graceful_degradation_notes": "10yr vs Ibbotson ~20yr — duration spread sensitivity"},
    "DAMODARAN_rbcorplt_Baa": {"agency": "Aswath Damodaran, NYU Stern",
                                 "publication": "Historical Returns (Baa Corporate Bond column)",
                                 "full_title": "Damodaran Baa corporate bond yield (proxy for LT Corp total return)",
                                 "table_id": "histretSP.html col Baa Corporate Bond",
                                 "frequency": "annual", "native_units": "percent_yield",
                                 "license": "Open academic", "retrieval_method": "live_html",
                                 "url": "https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/histretSP.html",
                                 "discontinued": False, "graceful_degradation_notes": "PROXY for Ibbotson rbcorplt; one credit notch below Aaa; omits capital-gain component"},
    "FRED_AAA_proxy_LTcorp": {"agency": "FRB/Moody's via FRED",
                                "publication": "FRED AAA used as PROXY for LT corp total return extension",
                                "full_title": "AAA yield proxy for LT corp total return",
                                "table_id": "AAA (PROXY interpretation)",
                                "frequency": "monthly->annual", "native_units": "percent_yield",
                                "license": "FRED Terms of Use", "retrieval_method": "live_csv",
                                "url": "https://fred.stlouisfed.org/graph/fredgraph.csv?id=AAA",
                                "discontinued": False, "graceful_degradation_notes": "PROXY for Ibbotson rbcorplt; omits capital-gain component"},
    "INTROPPRICE_rreq": {"agency": "Shaikh (derived Shiller+BEA)", "publication": "App 10.2 IntroPPrice col 28",
                          "full_title": "Real equity rate of return rreq",
                          "table_id": "Appendix10_IntroPPrice.xlsx col 28",
                          "frequency": "annual", "native_units": "rate_decimal",
                          "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                          "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                          "discontinued": False, "graceful_degradation_notes": "Extension deferred to Phase 6"},
    "INTROPPRICE_iropcorp": {"agency": "Shaikh (BEA NIPA)", "publication": "App 10.2 IntroPPrice col 29",
                              "full_title": "Adjusted corporate real IROP",
                              "table_id": "Appendix10_IntroPPrice.xlsx col 29",
                              "frequency": "annual", "native_units": "rate_decimal",
                              "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                              "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                              "discontinued": False, "graceful_degradation_notes": ""},
    "INTROPPRICE_iropcorpnipa": {"agency": "Shaikh (BEA NIPA)", "publication": "App 10.2 IntroPPrice col 30",
                                  "full_title": "NIPA corporate real IROP",
                                  "table_id": "Appendix10_IntroPPrice.xlsx col 30",
                                  "frequency": "annual", "native_units": "rate_decimal",
                                  "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                                  "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                                  "discontinued": False, "graceful_degradation_notes": ""},
    "INTROPPRICE_preq": {"agency": "Shaikh (Shiller P / BEA deflator)", "publication": "App 10.2 IntroPPrice col 25",
                          "full_title": "Real S&P composite price preq",
                          "table_id": "Appendix10_IntroPPrice.xlsx col 25",
                          "frequency": "annual", "native_units": "index_real_BEA_deflator",
                          "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                          "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                          "discontinued": False, "graceful_degradation_notes": ""},
    "INTROPPRICE_dvr": {"agency": "Shaikh (Shiller D / BEA deflator)", "publication": "App 10.2 IntroPPrice col 26",
                         "full_title": "Real S&P composite dividend dvr",
                         "table_id": "Appendix10_IntroPPrice.xlsx col 26",
                         "frequency": "annual", "native_units": "index_real_BEA_deflator",
                         "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                         "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                         "discontinued": False, "graceful_degradation_notes": ""},
    "INTROPPRICE_prstarshiller1": {"agency": "Shiller P* re-deflated", "publication": "App 10.2 IntroPPrice col 38",
                                    "full_title": "Shiller P* (constant r=7.6%) re-deflated by BEA pIGcorpbea",
                                    "table_id": "Appendix10_IntroPPrice.xlsx col 38",
                                    "frequency": "annual", "native_units": "index_real_BEA_deflator",
                                    "license": "Academic free-use + Shaikh adaptation",
                                    "retrieval_method": "salvaged_local_xlsx",
                                    "url": "http://www.econ.yale.edu/~shiller/data.htm",
                                    "discontinued": False, "graceful_degradation_notes": "Pinned to 2014 r=7.6% vintage"},
    "INTROPPRICE_prweq_book": {"agency": "Shaikh (eq 10.31)", "publication": "App 10.2 IntroPPrice col 33",
                                 "full_title": "Warranted real equity price prweq (book-published)",
                                 "table_id": "Appendix10_IntroPPrice.xlsx col 33",
                                 "frequency": "annual", "native_units": "index_real_BEA_deflator",
                                 "license": "Author-distributed academic", "retrieval_method": "salvaged_local_xlsx",
                                 "url": "https://web.archive.org/web/20240311145229/https://www.anwarshaikhecon.org/",
                                 "discontinued": False, "graceful_degradation_notes": "V03 validation only"},
    "S1002_components_book": {"agency": "Internal (formula)",
                                "publication": "Recomputed from S1002 book components in P02",
                                "full_title": "S1002 book components for S1003 ratio (No-Lazy-Splices)",
                                "table_id": "internal", "frequency": "annual", "native_units": "ratio_1947=1",
                                "license": "n/a", "retrieval_method": "internal_computed",
                                "url": None, "discontinued": False, "graceful_degradation_notes": ""},
    "S1002_components_extended": {"agency": "Internal (formula)",
                                    "publication": "Recomputed from extended FRED components in P02",
                                    "full_title": "S1002 extended components for S1003 ratio post-2011",
                                    "table_id": "internal", "frequency": "annual", "native_units": "ratio_1947=1",
                                    "license": "n/a", "retrieval_method": "internal_computed",
                                    "url": None, "discontinued": False, "graceful_degradation_notes": ""},
    "S1002_components": {"agency": "Internal (S1002 panel)",
                          "publication": "S1002 panel used by P02_S1004",
                          "full_title": "S1002 panel (book+ext) for S1004",
                          "table_id": "internal", "frequency": "annual", "native_units": "percent",
                          "license": "n/a", "retrieval_method": "internal_computed",
                          "url": None, "discontinued": False, "graceful_degradation_notes": ""},
    "HP_filter_lambda_3": {"agency": "Internal (HP filter)",
                            "publication": "Hodrick-Prescott (1997) two-sided, lambda=3 (Shaikh choice)",
                            "full_title": "HP trend of iblongreal, lambda=3",
                            "table_id": "internal", "frequency": "annual", "native_units": "percent",
                            "license": "n/a", "retrieval_method": "internal_computed",
                            "url": None, "discontinued": False, "graceful_degradation_notes": "End-to-end recompute on extension"},
    "HP_filter_lambda_6.25": {"agency": "Internal (HP filter)",
                                "publication": "Ravn-Uhlig (2002) standard for annual, lambda=6.25",
                                "full_title": "HP trend of iblongreal, lambda=6.25",
                                "table_id": "internal", "frequency": "annual", "native_units": "percent",
                                "license": "n/a", "retrieval_method": "internal_computed",
                                "url": None, "discontinued": False, "graceful_degradation_notes": ""},
    "eq_10.31_recursion": {"agency": "Internal (eq 10.31)",
                            "publication": "Shaikh Ch 10 eq 10.31 forward iteration",
                            "full_title": "Warranted real equity price recursion (footnote 24 pinned)",
                            "table_id": "internal", "frequency": "annual", "native_units": "index_real_BEA_deflator",
                            "license": "n/a", "retrieval_method": "internal_computed",
                            "url": None, "discontinued": False,
                            "graceful_degradation_notes": "NORMALIZATION_INTERVAL pinned per footnote 24"},
}

added = 0
for k, v in NEW_SUBS.items():
    if k not in meta.setdefault("subsources", {}):
        meta["subsources"][k] = v
        added += 1
    else:
        # Update in place if exists (idempotent re-run)
        meta["subsources"][k].update(v)

META.write_text(json.dumps(meta, indent=2, default=str), encoding="utf-8")
print(f"SUBSOURCE_METADATA: added {added} new + updated {len(NEW_SUBS) - added} existing.")

for sid in CH10:
    led.setdefault("series", {})[sid] = {
        "name": reg["series"][sid]["name"],
        "chapter": 10,
        "status": "ingested",
        "phases_completed": ["3_research", "4_adequacy", "5_ingestion", "6_extension", "7_replication", "8_output"],
        "artifacts": {
            "research_json": f"Technical/research/{sid}_research.json",
            "adequacy_report": "Technical/docs/chapters/CH10_ADEQUACY_REPORT.json",
            "dpr": f"Technical/docs/series/{sid}_DPR.md",
            "epr": f"Technical/docs/series/{sid}_EPR.md",
            "loader": f"Technical/code/L01_loaders/L01_{sid}_load.py",
            "processor": f"Technical/code/P02_processors/P02_{sid}_construct.py",
            "validator": f"Technical/code/V03_validators/V03_{sid}_validate.py",
            "processed": f"Technical/data/processed/{sid}.parquet",
            "chopped_csv": f"Technical/chopped/{sid}.csv",
            "extenbook_xlsx": f"Technical/extenbooks/{sid}_extenbook.xlsx",
        },
        "subseries_ids": sorted(reg["series"][sid]["subseries"].keys()),
        "subsource_ids": sorted({sub["subsource_id"] for sub in reg["series"][sid]["subseries"].values()
                                  if sub.get("subsource_id")}),
    }
LED.write_text(json.dumps(led, indent=2, default=str), encoding="utf-8")
print("ANU_LEDGER updated for 8 CH10 series.")
