"""Bulk register update for the 8 External Study (ES) series.

Idempotent. Updates registry, SUBSOURCE_METADATA, and ANU_LEDGER for:
  ES2001, ES2101, ES2201, ES2301, ES2302, ES2303, ES2304, ES2305
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import paths  # type: ignore

ES_UPDATES = {
    "ES2001": {
        "name": "Shaikh (2020) Sraffa Price-Value Aggregates, US 1947-1998 (Tables 1-2)",
        "units": "dimensionless_ratio",
        "construction": "composite",
        "content_type": "time_series",
        "status": "ingested",
        "year_range": [1947, 1998],
        "year_range_book": [1947, 1998],
        "year_range_extension": [1947, 2017],
        "dpr": "Technical/docs/series/ES2001_DPR.md",
        "epr": "Technical/docs/series/ES2001_EPR.md",
        "primary_source": "SHAIKH_2020_SRAFFA_PRICES_T1T2",
        "subseries": {
            "ES2001-circ-rate_profit": {
                "name": "Circulating capital rate of profit ratio",
                "subsource_id": "SHAIKH_2020_SRAFFA_PRICES_T1T2",
                "source": "Shaikh (2020) Table 1",
                "source_url": None,
                "period": [1947, 1998], "native_units": "dimensionless_ratio",
                "units": "dimensionless_ratio", "is_reindexed": False,
                "color": "#1f77b4", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None,
            },
            "ES2001-fixed-rate_profit": {
                "name": "Fixed capital rate of profit ratio",
                "subsource_id": "SHAIKH_2020_SRAFFA_PRICES_T1T2",
                "source": "Shaikh (2020) Table 2",
                "source_url": None,
                "period": [1947, 1998], "native_units": "dimensionless_ratio",
                "units": "dimensionless_ratio", "is_reindexed": False,
                "color": "#ff7f0e", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None,
            },
        },
    },
    "ES2101": {
        "name": "Shaikh-Coronado-Nassif-Pires (2020) Sraffa CI/Theil Summary Stats",
        "units": "mixed_dimensionless_count_percent",
        "construction": "composite",
        "content_type": "derived",
        "status": "ingested",
        "year_range": [2002, 2007],
        "year_range_book": [2002, 2007],
        "year_range_extension": [2002, 2017],
        "dpr": "Technical/docs/series/ES2101_DPR.md",
        "epr": "Technical/docs/series/ES2101_EPR.md",
        "primary_source": "SHAIKH_CORONADO_NASSIF_2020_S5_SUMMARY",
        "subseries": {
            "ES2101-avg_CI_lower_bound": {
                "name": "Average CI lower bound across aggregation levels",
                "subsource_id": "SHAIKH_CORONADO_NASSIF_2020_S5_SUMMARY",
                "source": "Shaikh-Coronado-Nassif-Pires (2020) Section 5 p. 272",
                "source_url": "https://doi.org/10.4337/ejeep.2020.0069",
                "period": [2002, 2007], "native_units": "dimensionless",
                "units": "dimensionless", "is_reindexed": False,
                "color": "#1f77b4", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None,
            },
        },
    },
    "ES2201": {
        "name": "Shaikh-Jacobo (2020) Econophysics Two-Class Income Parameters, US 2002-2016",
        "units": "mixed_dimensionless_thousandsusd",
        "construction": "composite",
        "content_type": "time_series",
        "status": "ingested",
        "year_range": [2002, 2016],
        "year_range_book": [2002, 2016],
        "year_range_extension": [2002, 2022],
        "dpr": "Technical/docs/series/ES2201_DPR.md",
        "epr": "Technical/docs/series/ES2201_EPR.md",
        "primary_source": "SHAIKH_JACOBO_2020_TABLE1",
        "subseries": {
            "ES2201-G_prime": {"name": "Gini coefficient bottom 97%",
                "subsource_id": "SHAIKH_JACOBO_2020_TABLE1",
                "source": "Shaikh-Jacobo (2020) Table 1 col G'",
                "source_url": "https://doi.org/10.1561/105.00000129",
                "period": [2002, 2016], "native_units": "dimensionless",
                "units": "dimensionless", "is_reindexed": False,
                "color": "#1f77b4", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
            "ES2201-r_mean": {"name": "Overall mean AGI per return",
                "subsource_id": "SHAIKH_JACOBO_2020_TABLE1",
                "source": "Shaikh-Jacobo (2020) Table 1 col r-mean",
                "source_url": "https://doi.org/10.1561/105.00000129",
                "period": [2002, 2016], "native_units": "thousands_usd",
                "units": "thousands_usd", "is_reindexed": False,
                "color": "#ff7f0e", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
            "ES2201-w_mean": {"name": "Bottom-97% mean / income temperature",
                "subsource_id": "SHAIKH_JACOBO_2020_TABLE1",
                "source": "Shaikh-Jacobo (2020) Table 1 col w-mean",
                "source_url": "https://doi.org/10.1561/105.00000129",
                "period": [2002, 2016], "native_units": "thousands_usd",
                "units": "thousands_usd", "is_reindexed": False,
                "color": "#2ca02c", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
            "ES2201-f_top3": {"name": "Top-3% income share (derived 1-w/r)",
                "subsource_id": "SHAIKH_JACOBO_2020_TABLE1",
                "source": "Shaikh-Jacobo (2020) Table 1 col f",
                "source_url": "https://doi.org/10.1561/105.00000129",
                "period": [2002, 2016], "native_units": "dimensionless",
                "units": "dimensionless", "is_reindexed": False,
                "color": "#d62728", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
            "ES2201-alpha": {"name": "Top-3% power-law exponent",
                "subsource_id": "SHAIKH_JACOBO_2020_TABLE1",
                "source": "Shaikh-Jacobo (2020) Table 1 col alpha",
                "source_url": "https://doi.org/10.1561/105.00000129",
                "period": [2002, 2016], "native_units": "dimensionless",
                "units": "dimensionless", "is_reindexed": False,
                "color": "#9467bd", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
        },
    },
    "ES2301": {
        "name": "Weber-Shaikh (2020) Fig 1 — US Trade Balance vs World and China",
        "units": "billion_usd",
        "construction": "direct",
        "content_type": "time_series",
        "status": "ingested",
        "year_range": [2002, 2024],
        "year_range_book": [2002, 2017],
        "year_range_extension": [2018, 2024],
        "dpr": "Technical/docs/series/ES2301_DPR.md",
        "epr": "Technical/docs/series/ES2301_EPR.md",
        "primary_source": "CENSUS_FT900_EXH1",
        "subseries": {
            "ES2301-world": {"name": "US-World goods trade balance (Census basis)",
                "subsource_id": "CENSUS_FT900_EXH1",
                "source": "US Census FT900 Exhibit 1 (historical)",
                "source_url": "https://www.census.gov/foreign-trade/statistics/historical/exh1.txt",
                "period": [2002, 2024], "native_units": "millions_usd",
                "units": "billion_usd", "is_reindexed": False,
                "color": "#1f77b4", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
            "ES2301-china": {"name": "US-China bilateral goods trade balance",
                "subsource_id": "CENSUS_FT900_C5700",
                "source": "US Census FT900 Exhibit 14 / c5700",
                "source_url": "https://www.census.gov/foreign-trade/balance/c5700.html",
                "period": [2002, 2024], "native_units": "millions_usd",
                "units": "billion_usd", "is_reindexed": False,
                "color": "#d62728", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
        },
    },
    "ES2302": {
        "name": "Weber-Shaikh (2020) Fig 2 — China Current Account Balance (level + %GDP)",
        "units": "billion_usd_and_percent_gdp",
        "construction": "direct",
        "content_type": "time_series",
        "status": "ingested",
        "year_range": [1997, 2024],
        "year_range_book": [1997, 2017],
        "year_range_extension": [2018, 2024],
        "dpr": "Technical/docs/series/ES2302_DPR.md",
        "epr": "Technical/docs/series/ES2302_EPR.md",
        "primary_source": "IMF_WEO_BCA_CHN",
        "subseries": {
            "ES2302-level": {"name": "China CA balance (billions USD)",
                "subsource_id": "IMF_WEO_BCA_CHN",
                "source": "IMF WEO subject BCA (CA balance, USD bn)",
                "source_url": "https://www.imf.org/external/datamapper/BCA@WEO/CHN",
                "period": [1997, 2024], "native_units": "billion_usd",
                "units": "billion_usd", "is_reindexed": False,
                "color": "#1f77b4", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
            "ES2302-pctgdp": {"name": "China CA balance (% of nominal GDP)",
                "subsource_id": "IMF_WEO_BCA_NGDPD_CHN",
                "source": "IMF WEO subject BCA_NGDPD (CA % GDP)",
                "source_url": "https://www.imf.org/external/datamapper/BCA_NGDPD@WEO/CHN",
                "period": [1997, 2024], "native_units": "percent_of_nominal_gdp",
                "units": "percent_of_nominal_gdp", "is_reindexed": False,
                "color": "#ff7f0e", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
        },
    },
    "ES2303": {
        "name": "Weber-Shaikh (2020) Fig 3 — China FX Reserves ex-Gold (WDI)",
        "units": "billion_usd",
        "construction": "direct",
        "content_type": "time_series",
        "status": "ingested",
        "year_range": [1990, 2024],
        "year_range_book": [1990, 2016],
        "year_range_extension": [2017, 2024],
        "dpr": "Technical/docs/series/ES2303_DPR.md",
        "epr": "Technical/docs/series/ES2303_EPR.md",
        "primary_source": "WB_FI_RES_XGLD_CD_CHN",
        "subseries": {
            "ES2303-A": {"name": "China total reserves ex gold (WDI FI.RES.XGLD.CD)",
                "subsource_id": "WB_FI_RES_XGLD_CD_CHN",
                "source": "World Bank WDI FI.RES.XGLD.CD",
                "source_url": "https://data.worldbank.org/indicator/FI.RES.XGLD.CD",
                "period": [1990, 2024], "native_units": "current_usd",
                "units": "billion_usd", "is_reindexed": False,
                "color": "#1f77b4", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
        },
    },
    "ES2304": {
        "name": "Weber-Shaikh (2020) Fig 4 — RMB Misalignment Extended PPP (literature compilation)",
        "units": "percent",
        "construction": "composite",
        "content_type": "derived",
        "status": "ingested",
        "year_range": [1999, 2010],
        "year_range_book": [1999, 2010],
        "year_range_extension": [1999, 2010],
        "extension_status": "not_applicable_literature_compilation",
        "dpr": "Technical/docs/series/ES2304_DPR.md",
        "epr": "Technical/docs/series/ES2304_EPR.md",
        "primary_source": "WEBER_SHAIKH_2020_FIG4_LIT_COMPILATION",
        "subseries": {
            "ES2304-A": {"name": "Extended-PPP RMB misalignment estimates (named endpoints)",
                "subsource_id": "WEBER_SHAIKH_2020_FIG4_LIT_COMPILATION",
                "source": "Literature compilation per paper note 17",
                "source_url": "https://www.piie.com/sites/default/files/publications/pb/pb07-4.pdf",
                "period": [1999, 2010], "native_units": "percent",
                "units": "percent", "is_reindexed": False,
                "color": "#1f77b4", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
        },
    },
    "ES2305": {
        "name": "Weber-Shaikh (2020) Fig 5 — RMB Misalignment Macro Balance (literature compilation)",
        "units": "percent",
        "construction": "composite",
        "content_type": "derived",
        "status": "ingested",
        "year_range": [1999, 2012],
        "year_range_book": [1999, 2012],
        "year_range_extension": [1999, 2012],
        "extension_status": "not_applicable_literature_compilation",
        "dpr": "Technical/docs/series/ES2305_DPR.md",
        "epr": "Technical/docs/series/ES2305_EPR.md",
        "primary_source": "WEBER_SHAIKH_2020_FIG5_LIT_COMPILATION",
        "subseries": {
            "ES2305-A": {"name": "Macro-balance RMB misalignment estimates (named endpoints)",
                "subsource_id": "WEBER_SHAIKH_2020_FIG5_LIT_COMPILATION",
                "source": "Literature compilation per paper note 17",
                "source_url": "https://www.piie.com/sites/default/files/publications/pb/pb07-4.pdf",
                "period": [1999, 2012], "native_units": "percent",
                "units": "percent", "is_reindexed": False,
                "color": "#d62728", "role": "book_period_primary",
                "proxy": False, "proxy_justification": None},
        },
    },
}


SUBSOURCE_UPDATES = {
    "SHAIKH_2020_SRAFFA_PRICES_T1T2": {
        "full_title": "Shaikh (2020) An Empirically Sufficient Form for Sraffa Prices, Tables 1-2",
        "agency": "Author working paper (festschrift for Pasinetti)",
        "publisher": "Palgrave Macmillan (Velupillai ed.)",
        "publication_year": 2020,
        "table_id": "Tables 1 and 2",
        "table_title": "Ratios of Price and Value Aggregates at Observed Rates of Profit",
        "page": 10,
        "frequency": "irregular (1947, 1958, 1963, 1967, 1972, 1998)",
        "native_units": "dimensionless ratios in [0.94, 1.08]",
        "release_schedule": "one-time festschrift essay",
        "license": "academic-quotation / fair use of published table",
        "retrieval_method": "salvaged_chopped_table",
        "retrieval_location": "SalvagedInputs/book_data/Reconstructed/ES2001_aggregate_ratios.csv",
        "url": None,
        "url_status": "anwarshaikhecon.org_DNS_fail_substituted_with_archival_pdf",
        "discontinued": False,
        "replaced_by": None,
        "notes": "Underlying primary data: BEA Benchmark IO + BLS labor compensation + Shaikh 1998/2012 appendices.",
    },
    "SHAIKH_CORONADO_NASSIF_2020_S5_SUMMARY": {
        "full_title": "Shaikh-Coronado-Nassif-Pires (2020) On the empirical regularities of Sraffa prices",
        "agency": "EJEEP / Edward Elgar",
        "publisher": "Edward Elgar (EJEEP)",
        "publication_year": 2020,
        "table_id": "Section 5 conclusions (p. 272) — verbatim summary statistics",
        "table_title": "Average CI ranges and switching counts (2002, 2007)",
        "page": 272,
        "frequency": "single benchmark years 2002 and 2007",
        "native_units": "mixed (dimensionless, count, percent)",
        "release_schedule": "one-time journal article",
        "license": "fair use of summary statistics quoted in paper text",
        "retrieval_method": "salvaged_chopped_table",
        "retrieval_location": "SalvagedInputs/book_data/Reconstructed/ES2101_summary_statistics.csv",
        "url": "https://doi.org/10.4337/ejeep.2020.0069",
        "url_status": "doi_resolves_in_browser_403_to_HEAD_bot",
        "discontinued": False,
        "replaced_by": None,
        "notes": "Full CI/Theil scatter (Figs 6 and 7) requires shared BEA-Sraffa pipeline (v1.1).",
    },
    "SHAIKH_JACOBO_2020_TABLE1": {
        "full_title": "Shaikh-Jacobo (2020) Economic Arbitrage and the Econophysics of Income Inequality, Table 1",
        "agency": "Review of Behavioral Economics (now Publishers)",
        "publisher": "now Publishers",
        "publication_year": 2020,
        "table_id": "Table 1",
        "table_title": "Annual fitted parameters G', r-mean, w-mean, f, alpha for 2002-2016",
        "page": 5,
        "frequency": "annual",
        "native_units": "mixed (dimensionless, thousands USD)",
        "release_schedule": "one-time journal article",
        "license": "fair use of published table",
        "retrieval_method": "salvaged_chopped_table",
        "retrieval_location": "SalvagedInputs/book_data/Reconstructed/ES2201_fitted_parameters.csv",
        "url": "https://doi.org/10.1561/105.00000129",
        "url_status": "doi_resolves_in_browser",
        "discontinued": False,
        "replaced_by": None,
        "notes": "Underlying primary data: IRS SOI Pub 1304 Tables 1.4 and 1 (US Federal Gov public domain, 17 USC 105).",
    },
    "CENSUS_FT900_EXH1": {
        "full_title": "US Census FT900 Exhibit 1 — US Total Goods Trade",
        "agency": "U.S. Census Bureau, Foreign Trade Division",
        "publisher": "U.S. Census Bureau",
        "publication_year": None,
        "table_id": "FT900 Exhibit 1 / historical exh1.txt",
        "table_title": "U.S. International Trade in Goods and Services, Total",
        "page": None,
        "frequency": "annual (computed from monthly FT900)",
        "native_units": "millions current USD",
        "release_schedule": "monthly",
        "license": "Public domain (US Federal Government, 17 USC 105)",
        "retrieval_method": "api_open_no_auth",
        "retrieval_location": "S00_apis.census_ft900_annual_balance(partner='world')",
        "url": "https://www.census.gov/foreign-trade/statistics/historical/exh1.txt",
        "url_status": "200",
        "discontinued": False,
        "replaced_by": None,
        "notes": "Census-basis (Total Exports Value - Customs Import Value), not BoP-basis.",
    },
    "CENSUS_FT900_C5700": {
        "full_title": "US Census FT900 Trade in Goods with China (per-country page c5700)",
        "agency": "U.S. Census Bureau, Foreign Trade Division",
        "publisher": "U.S. Census Bureau",
        "publication_year": None,
        "table_id": "Per-country balance page c5700",
        "table_title": "Trade in Goods with China",
        "page": None,
        "frequency": "annual (computed from monthly FT900)",
        "native_units": "millions current USD",
        "release_schedule": "monthly",
        "license": "Public domain",
        "retrieval_method": "api_open_no_auth",
        "retrieval_location": "S00_apis.census_ft900_annual_balance(partner='5700')",
        "url": "https://www.census.gov/foreign-trade/balance/c5700.html",
        "url_status": "200",
        "discontinued": False,
        "replaced_by": None,
        "notes": "FT900 Exhibit 14 underlying microdata.",
    },
    "IMF_WEO_BCA_CHN": {
        "full_title": "IMF World Economic Outlook subject BCA for China",
        "agency": "International Monetary Fund",
        "publisher": "IMF",
        "publication_year": None,
        "table_id": "WEO BCA / CHN",
        "table_title": "Current account balance, billions USD",
        "page": None,
        "frequency": "annual",
        "native_units": "billion USD",
        "release_schedule": "semi-annual (April + October)",
        "license": "IMF terms permit research replication with attribution",
        "retrieval_method": "api_open_no_auth",
        "retrieval_location": "S00_apis.imf_weo_country('CHN', ('BCA',))",
        "url": "https://www.imf.org/external/datamapper/api/v1/BCA/CHN",
        "url_status": "200",
        "discontinued": False,
        "replaced_by": None,
        "notes": "Paper used 2018 WEO vintage; modern vintages have minor historical revisions.",
    },
    "IMF_WEO_BCA_NGDPD_CHN": {
        "full_title": "IMF World Economic Outlook subject BCA_NGDPD for China",
        "agency": "International Monetary Fund",
        "publisher": "IMF",
        "publication_year": None,
        "table_id": "WEO BCA_NGDPD / CHN",
        "table_title": "Current account balance as percent of nominal GDP",
        "page": None,
        "frequency": "annual",
        "native_units": "percent of GDP",
        "release_schedule": "semi-annual",
        "license": "IMF terms",
        "retrieval_method": "api_open_no_auth",
        "retrieval_location": "S00_apis.imf_weo_country('CHN', ('BCA_NGDPD',))",
        "url": "https://www.imf.org/external/datamapper/api/v1/BCA_NGDPD/CHN",
        "url_status": "200",
        "discontinued": False,
        "replaced_by": None,
        "notes": None,
    },
    "WB_FI_RES_XGLD_CD_CHN": {
        "full_title": "World Bank WDI FI.RES.XGLD.CD (Total reserves minus gold) for China",
        "agency": "World Bank",
        "publisher": "World Bank",
        "publication_year": None,
        "table_id": "WDI FI.RES.XGLD.CD / CHN",
        "table_title": "Total reserves minus gold (current US$), China",
        "page": None,
        "frequency": "annual",
        "native_units": "current USD",
        "release_schedule": "rolling annual update",
        "license": "CC-BY-4.0 (World Bank Open Data Terms)",
        "retrieval_method": "api_open_no_auth",
        "retrieval_location": "S00_apis.worldbank_indicator('CHN', 'FI.RES.XGLD.CD')",
        "url": "https://api.worldbank.org/v2/country/CHN/indicator/FI.RES.XGLD.CD?format=json",
        "url_status": "200",
        "discontinued": False,
        "replaced_by": None,
        "notes": "Loader divides current USD by 1e9 for Billion-USD presentation.",
    },
    "WEBER_SHAIKH_2020_FIG4_LIT_COMPILATION": {
        "full_title": "Weber-Shaikh (2020) Fig 4 literature compilation per paper note 17",
        "agency": "Authors (literature compilation)",
        "publisher": None,
        "publication_year": 2020,
        "table_id": "Fig 4 scatter (Appendix p. 454)",
        "table_title": "Estimates of RMB misalignment based on extended PPP approach",
        "page": 454,
        "frequency": "irregular (1999-2010)",
        "native_units": "percent",
        "release_schedule": "one-time journal article",
        "license": "fair-use academic compilation",
        "retrieval_method": "salvaged_chopped_table",
        "retrieval_location": "SalvagedInputs/book_data/Reconstructed/ES2304_literature_compilation.csv",
        "url": None,
        "url_status": None,
        "discontinued": False,
        "replaced_by": None,
        "notes": "v1.0 named endpoints only; full ~35-point scatter deferred to v1.1.",
    },
    "WEBER_SHAIKH_2020_FIG5_LIT_COMPILATION": {
        "full_title": "Weber-Shaikh (2020) Fig 5 literature compilation per paper note 17",
        "agency": "Authors (literature compilation)",
        "publisher": None,
        "publication_year": 2020,
        "table_id": "Fig 5 scatter (Appendix p. 455)",
        "table_title": "Estimates of RMB misalignment based on macroeconomic balance approach",
        "page": 455,
        "frequency": "irregular (1999-2012)",
        "native_units": "percent",
        "release_schedule": "one-time journal article",
        "license": "fair-use academic compilation",
        "retrieval_method": "salvaged_chopped_table",
        "retrieval_location": "SalvagedInputs/book_data/Reconstructed/ES2305_literature_compilation.csv",
        "url": None,
        "url_status": None,
        "discontinued": False,
        "replaced_by": None,
        "notes": "v1.0 named endpoints only; full ~30-point scatter deferred to v1.1.",
    },
}


def main():
    reg = json.loads(paths.REGISTRY.read_text(encoding="utf-8"))
    meta = json.loads(paths.SUBSOURCE_METADATA.read_text(encoding="utf-8"))
    ledger = json.loads(paths.LEDGER.read_text(encoding="utf-8"))

    # Series registry update
    for sid, upd in ES_UPDATES.items():
        existing = reg["series"].get(sid, {})
        existing.update(upd)
        # Preserve subseries if not in update
        reg["series"][sid] = existing

    # Subsource metadata
    if "subsources" not in meta:
        meta["subsources"] = {}
    for ssid, mdata in SUBSOURCE_UPDATES.items():
        meta["subsources"][ssid] = mdata

    # Ledger
    if "series" not in ledger:
        ledger["series"] = {}
    for sid in ES_UPDATES.keys():
        ledger["series"][sid] = {
            "phases_completed": [5, 6, 7],
            "artifacts": {
                "dpr": f"Technical/docs/series/{sid}_DPR.md",
                "epr": f"Technical/docs/series/{sid}_EPR.md",
                "loader": f"Technical/code/L01_loaders/L01_{sid}_load.py",
                "processor": f"Technical/code/P02_processors/P02_{sid}_construct.py",
                "validator": f"Technical/code/V03_validators/V03_{sid}_validate.py",
            },
            "last_updated": "2026-05-18",
            "author": "opus-fanout-ES",
        }

    # Recompute counts
    from collections import Counter
    by_ch: Counter = Counter()
    by_ct: Counter = Counter()
    by_status: Counter = Counter()
    for det in reg["series"].values():
        ch = det.get("chapter") or "ES"
        by_ch[str(ch)] += 1
        by_ct[str(det.get("content_type"))] += 1
        by_status[str(det.get("status"))] += 1
    reg["series_count"] = len(reg["series"])
    reg["by_chapter"] = dict(sorted(by_ch.items()))
    reg["by_content_type"] = dict(sorted(by_ct.items()))
    reg["by_status"] = dict(sorted(by_status.items()))

    paths.REGISTRY.write_text(json.dumps(reg, indent=2, ensure_ascii=False), encoding="utf-8")
    paths.SUBSOURCE_METADATA.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    paths.LEDGER.write_text(json.dumps(ledger, indent=2, ensure_ascii=False), encoding="utf-8")

    print(f"Updated registry: {len(ES_UPDATES)} ES series")
    print(f"Subsources added/updated: {len(SUBSOURCE_UPDATES)}")
    print(f"Ledger entries added: {len(ES_UPDATES)}")
    print(f"Registry now has {reg['series_count']} series; by_status={reg['by_status']}")


if __name__ == "__main__":
    main()
